# Generated by Django 6.1.1 on 2026-09-14 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Penalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("remark", "Замечание"),
                            ("battle_remark", "Боевое замечание"),
                            ("warning", "Предупреждение"),
                            ("battle_suspension", "Временное отстранение от боёв"),
                            ("temp_ban", "Временный бан"),
                            ("character_reset", "Обнуление персонажа"),
                            ("permanent_ban", "Бессрочный бан"),
                        ],
                        max_length=20,
                        verbose_name="тип",
                    ),
                ),
                ("reason", models.TextField(verbose_name="причина")),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="вынесено"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Для авто-сгорания замечаний/предупреждений",
                        null=True,
                        verbose_name="сгорает",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активно"),
                            ("expired", "Сгорело"),
                            ("cancelled", "Отменено"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(blank=True, verbose_name="причина отмены"),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_penalties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто отменил",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_penalties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто вынес",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "взыскание",
                "verbose_name_plural": "взыскания",
                "ordering": ["-issued_at"],
                "permissions": [
                    ("can_issue_penalties", "Может выносить взыскания"),
                    ("can_cancel_penalties", "Может отменять взыскания"),
                    (
                        "can_view_penalties",
                        "Может просматривать чужую историю взысканий",
                    ),
                ],
            },
        ),
    ]
