# Generated by Django 6.1.1 on 2026-09-14 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0001_initial"),
        ("penalties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="penalty",
            name="related_battle",
            field=models.ForeignKey(
                blank=True,
                help_text="Если взыскание вынесено по итогам конкретного боя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="penalties",
                to="battles.battle",
                verbose_name="связанный бой",
            ),
        ),
    ]
