# Generated by Django 6.1.1 on 2026-09-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("penalties", "0002_penalty_related_battle"),
    ]

    operations = [
        migrations.AddField(
            model_name="penalty",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="отменено"),
        ),
    ]
