# Generated by Django 6.1.1 on 2026-09-15 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("user_registered", "Новая регистрация"),
                            ("displayname_request", "Запрос на смену никнейма"),
                            ("rank_request", "Заявка на повышение ранга"),
                            ("rank_changed", "Изменение ранга"),
                            ("battle_recorded", "Записан бой"),
                            ("monster_kill_recorded", "Записано убийство монстра"),
                            ("currency_granted", "Начислена валюта"),
                        ],
                        max_length=30,
                        verbose_name="тип",
                    ),
                ),
                (
                    "related_object_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="id связанного объекта"
                    ),
                ),
                ("message", models.TextField(verbose_name="сообщение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто совершил",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кого касается",
                    ),
                ),
            ],
            options={
                "verbose_name": "событие ленты",
                "verbose_name_plural": "лента событий",
                "ordering": ["-created_at"],
            },
        ),
    ]
