# Generated by Django 6.1.1 on 2026-09-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylogentry",
            name="type",
            field=models.CharField(
                choices=[
                    ("user_registered", "Новая регистрация"),
                    ("displayname_request", "Запрос на смену никнейма"),
                    ("displayname_reviewed", "Заявка на смену никнейма рассмотрена"),
                    ("rank_request", "Заявка на повышение ранга"),
                    ("rank_request_reviewed", "Заявка на ранг рассмотрена"),
                    ("rank_changed", "Изменение ранга"),
                    ("battle_recorded", "Записан бой"),
                    ("monster_kill_recorded", "Записано убийство монстра"),
                    ("currency_granted", "Начислена валюта"),
                    ("currency_transferred", "Перевод валюты между пользователями"),
                    ("penalty_issued", "Вынесено взыскание"),
                    ("penalty_cancelled", "Отменено взыскание"),
                    ("title_granted", "Выдан титул"),
                    ("title_revoked", "Отозван титул"),
                    ("bracket_generated", "Сгенерирована турнирная сетка"),
                    ("purchase_granted", "Товар выдан вручную"),
                    ("fundraiser_contribution", "Зафиксирован взнос в сбор средств"),
                ],
                max_length=30,
                verbose_name="тип",
            ),
        ),
    ]
