# Generated by Django 6.1.1 on 2026-09-14 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="название")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "reward_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="награда: опыт"
                    ),
                ),
                (
                    "reward_currency",
                    models.PositiveIntegerField(
                        default=0, verbose_name="награда: кроны"
                    ),
                ),
                (
                    "max_slots",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Сколько одинаковых копий доступно одновременно; пусто = без лимита",
                        null=True,
                        verbose_name="лимит одновременных копий",
                    ),
                ),
                (
                    "is_repeatable",
                    models.BooleanField(
                        default=False,
                        help_text="Может ли один пользователь брать это задание больше одного раза",
                        verbose_name="можно брать повторно",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активно"),
                ),
            ],
            options={
                "verbose_name": "задание",
                "verbose_name_plural": "задания",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "Выполняется"),
                            ("completed", "Выполнено"),
                            ("failed", "Провалено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="взято"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="завершено"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
                (
                    "task_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="tasks.tasktemplate",
                        verbose_name="задание",
                    ),
                ),
            ],
            options={
                "verbose_name": "выданное задание",
                "verbose_name_plural": "выданные задания",
                "ordering": ["-assigned_at"],
                "permissions": [
                    (
                        "can_manage_tasks",
                        "Может выдавать/закрывать задания за других и менять статусы",
                    )
                ],
            },
        ),
    ]
