# Generated by Django 6.1.1 on 2026-09-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="requirements",
            field=models.TextField(
                blank=True,
                help_text="Что нужно для взятия/выполнения квеста",
                verbose_name="требования",
            ),
        ),
    ]
