# Generated by Django 6.1.1 on 2026-09-14 15:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplayNameChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_name",
                    models.CharField(max_length=100, verbose_name="текущее имя"),
                ),
                (
                    "requested_name",
                    models.CharField(max_length=100, verbose_name="желаемое имя"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="причина")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="рассмотрена"
                    ),
                ),
            ],
            options={
                "verbose_name": "запрос на смену имени",
                "verbose_name_plural": "запросы на смену имени",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, verbose_name="email подтверждён"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Никнейм персонажа, свободный выбор при регистрации; далее меняется только через запрос",
                        max_length=100,
                        unique=True,
                        verbose_name="отображаемое имя",
                    ),
                ),
                (
                    "name_visibility",
                    models.CharField(
                        choices=[("hidden", "Скрыто"), ("public", "Публично")],
                        default="hidden",
                        max_length=10,
                        verbose_name="видимость имени и фамилии",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="аватар",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(default=1, verbose_name="уровень"),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(default=0, verbose_name="опыт"),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Внутриигровая валюта, начисляется только вручную через админку",
                        verbose_name="баланс, кроны",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата рождения"
                    ),
                ),
                (
                    "birth_date_visibility",
                    models.CharField(
                        choices=[
                            ("hidden", "Скрыто"),
                            ("day_month", "Только день и месяц"),
                            ("full", "Полностью"),
                        ],
                        default="hidden",
                        max_length=10,
                        verbose_name="видимость даты рождения",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
