# Generated by Django 6.1.1 on 2026-09-14 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("ranks", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                help_text="Изначально «Рекрут» — присваивается автоматически при регистрации",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="ranks.rank",
                verbose_name="ранг цеха",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="Изначально не назначена; назначается админом/мастером",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="schools.school",
                verbose_name="школа",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="displaynamechangerequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="кто рассмотрел",
            ),
        ),
        migrations.AddField(
            model_name="displaynamechangerequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="displayname_change_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
