# Generated by Django 6.1.1 on 2026-09-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_seed_default_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="название"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Например: школы ведьмаков, монстры, персонажи",
                        max_length=50,
                        verbose_name="категория",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="avatar_presets/", verbose_name="изображение"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
            ],
            options={
                "verbose_name": "пресет аватара",
                "verbose_name_plural": "пресеты аватаров",
                "ordering": ["category", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "starting_balance",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="стартовый баланс новых пользователей, кроны",
                    ),
                ),
            ],
            options={
                "verbose_name": "настройки сайта",
                "verbose_name_plural": "настройки сайта",
            },
        ),
    ]
