# Generated by Django 6.1.1 on 2026-09-15 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_avatarpreset_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="character_description",
            field=models.TextField(
                blank=True,
                help_text="Необязательная ролевая справка о персонаже — предыстория, характер и т.д.",
                verbose_name="описание персонажа",
            ),
        ),
        migrations.CreateModel(
            name="CurrencyTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="сумма, кроны")),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="сообщение"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="отправлено"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="currency_transfers_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="получатель",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="currency_transfers_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "перевод валюты",
                "verbose_name_plural": "переводы валюты",
                "ordering": ["-created_at"],
            },
        ),
    ]
