# Generated by Django 6.1.1 on 2026-09-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_character_description_currencytransfer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="displaynamechangerequest",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "can_review_displayname_requests",
                        "Может рассматривать заявки на смену никнейма",
                    )
                ],
                "verbose_name": "запрос на смену имени",
                "verbose_name_plural": "запросы на смену имени",
            },
        ),
    ]
