# Generated by Django 6.1.1 on 2026-09-14 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("battles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="название")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                ("date_start", models.DateField(verbose_name="дата начала")),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата окончания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Предстоит"),
                            ("ongoing", "Идёт"),
                            ("finished", "Завершён"),
                            ("cancelled", "Отменён"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "results_notes",
                    models.TextField(blank=True, verbose_name="итоги/примечания"),
                ),
                (
                    "bracket_generated",
                    models.BooleanField(
                        default=False, verbose_name="сетка сгенерирована"
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Проставляется автоматически по итогам финального матча сетки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournaments_won",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="победитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "турнир",
                "verbose_name_plural": "турниры",
                "ordering": ["-date_start"],
                "permissions": [
                    (
                        "can_manage_tournaments",
                        "Может управлять участниками, сеткой и результатами турниров",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TournamentParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed", models.PositiveIntegerField(verbose_name="номер посева")),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="tournaments.tournament",
                        verbose_name="турнир",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "участник турнира",
                "verbose_name_plural": "участники турнира",
                "ordering": ["seed"],
                "unique_together": {("tournament", "seed"), ("tournament", "user")},
            },
        ),
        migrations.CreateModel(
            name="TournamentMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveIntegerField(verbose_name="раунд")),
                (
                    "position",
                    models.PositiveIntegerField(verbose_name="позиция в раунде"),
                ),
                (
                    "battle",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament_match",
                        to="battles.battle",
                        verbose_name="бой",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournaments.tournament",
                        verbose_name="турнир",
                    ),
                ),
                (
                    "participant1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tournaments.tournamentparticipant",
                        verbose_name="участник 1",
                    ),
                ),
                (
                    "participant2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tournaments.tournamentparticipant",
                        verbose_name="участник 2",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tournaments.tournamentparticipant",
                        verbose_name="победитель матча",
                    ),
                ),
            ],
            options={
                "verbose_name": "матч сетки",
                "verbose_name_plural": "матчи сетки",
                "ordering": ["round_number", "position"],
                "unique_together": {("tournament", "round_number", "position")},
            },
        ),
    ]
