# Generated by Django 6.1.1 on 2026-09-15 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournamentmatch",
            options={
                "ordering": ["bracket", "round_number", "position"],
                "verbose_name": "матч сетки",
                "verbose_name_plural": "матчи сетки",
            },
        ),
        migrations.AlterUniqueTogether(
            name="tournamentmatch",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tournament",
            name="bracket_type",
            field=models.CharField(
                choices=[
                    ("single", "Одиночное выбывание"),
                    ("double", "Двойное выбывание (с нижней сеткой)"),
                ],
                default="single",
                max_length=10,
                verbose_name="формат сетки",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="runner_up",
            field=models.ForeignKey(
                blank=True,
                help_text="Проставляется автоматически — проигравший финального матча",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments_runner_up",
                to=settings.AUTH_USER_MODEL,
                verbose_name="второе место",
            ),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="bracket",
            field=models.CharField(
                choices=[
                    ("upper", "Верхняя сетка"),
                    ("lower", "Нижняя сетка"),
                    ("final", "Финал"),
                ],
                default="upper",
                max_length=10,
                verbose_name="сетка",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                help_text="Проставляется автоматически по итогам финального матча",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments_won",
                to=settings.AUTH_USER_MODEL,
                verbose_name="победитель (1 место)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentmatch",
            unique_together={("tournament", "bracket", "round_number", "position")},
        ),
        migrations.CreateModel(
            name="TournamentPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="tournaments/", verbose_name="изображение"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="подпись"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="tournaments.tournament",
                        verbose_name="турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото турнира",
                "verbose_name_plural": "фото турнира",
                "ordering": ["id"],
            },
        ),
    ]
