# Generated by Django 6.1.1 on 2026-09-14 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("battles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bestiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Например: низший вид / реликт / гибрид / проклятье",
                        max_length=100,
                        verbose_name="категория",
                    ),
                ),
                (
                    "danger_level",
                    models.CharField(
                        choices=[
                            ("low", "Низкая"),
                            ("medium", "Средняя"),
                            ("high", "Высокая"),
                            ("deadly", "Смертельная"),
                        ],
                        max_length=10,
                        verbose_name="уровень опасности",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="bestiary/",
                        verbose_name="изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "вид бестиария",
                "verbose_name_plural": "бестиарий",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MonsterKill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="дата"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="заметки")),
                (
                    "reward_granted",
                    models.BooleanField(
                        default=False, verbose_name="награда начислена"
                    ),
                ),
                (
                    "reward_experience",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="награда: опыт"
                    ),
                ),
                (
                    "reward_currency",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="награда: кроны"
                    ),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если убийство произошло в рамках боя/охоты",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monster_kills",
                        to="battles.battle",
                        verbose_name="бой",
                    ),
                ),
                (
                    "bestiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kills",
                        to="bestiary.bestiary",
                        verbose_name="вид монстра",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monster_kills_recorded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто зафиксировал",
                    ),
                ),
                (
                    "reward_granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monster_kill_rewards_granted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто начислил награду",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monster_kills",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "убитый монстр",
                "verbose_name_plural": "убитые монстры",
                "ordering": ["-date"],
                "permissions": [
                    (
                        "can_record_kills",
                        "Может фиксировать убийства монстров и начислять награды",
                    )
                ],
            },
        ),
    ]
