# Generated by Django 6.1.1 on 2026-09-14 16:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="название")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                ("date_start", models.DateField(verbose_name="дата начала")),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата окончания"
                    ),
                ),
            ],
            options={
                "verbose_name": "фестиваль",
                "verbose_name_plural": "фестивали",
                "ordering": ["-date_start"],
                "permissions": [
                    (
                        "can_manage_festivals",
                        "Может управлять фестивалями и их фотографиями",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="заголовок")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="слаг",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Если пусто — в списке постов показывается начало текста",
                        verbose_name="краткое превью",
                    ),
                ),
                ("content", models.TextField(verbose_name="текст")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/covers/",
                        verbose_name="обложка",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликован"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="опубликован когда",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "festival",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если пост написан о конкретном фестивале",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to="blog.festival",
                        verbose_name="фестиваль",
                    ),
                ),
            ],
            options={
                "verbose_name": "пост блога",
                "verbose_name_plural": "посты блога",
                "ordering": ["-published_at"],
                "permissions": [
                    (
                        "can_manage_blog",
                        "Может создавать/редактировать/удалять посты блога",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FestivalPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="festivals/", verbose_name="изображение"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="подпись"
                    ),
                ),
                (
                    "festival",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="blog.festival",
                        verbose_name="фестиваль",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото фестиваля",
                "verbose_name_plural": "фото фестиваля",
                "ordering": ["id"],
            },
        ),
    ]
