# Generated by Django 6.1.1 on 2026-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "price_real",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="цена, BYN"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
            ],
            options={
                "verbose_name": "разовая активность",
                "verbose_name_plural": "разовые активности",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "perks",
                    models.TextField(
                        blank=True,
                        help_text="Произвольные привилегии: приоритетная запись, гарантированные слоты, гость и т.д.",
                        verbose_name="привилегии",
                    ),
                ),
                (
                    "price_real",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="цена, BYN"
                    ),
                ),
                (
                    "price_currency",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Стоимость в кронах — опционально",
                        null=True,
                        verbose_name="цена, кроны",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(verbose_name="срок действия, дней"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
                (
                    "included_activities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subscriptions",
                        to="subscriptions.activityprice",
                        verbose_name="включённые активности",
                    ),
                ),
            ],
            options={
                "verbose_name": "абонемент",
                "verbose_name_plural": "абонементы",
                "ordering": ["price_real"],
            },
        ),
    ]
