# Generated by Django 6.1.1 on 2026-09-14 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ТС", "Тренировочная Схватка (на очки)"),
                            ("РС", "Ролевая Схватка (до поражения аватара)"),
                        ],
                        max_length=2,
                        verbose_name="тип боя",
                    ),
                ),
                (
                    "is_ranked",
                    models.BooleanField(
                        default=False,
                        help_text="Иначе — тренировочный бой",
                        verbose_name="ранговый/квестовый",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="дата и время"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="заметки")),
                (
                    "fighter1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="battles_as_fighter1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="участник 1",
                    ),
                ),
                (
                    "fighter2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="battles_as_fighter2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="участник 2",
                    ),
                ),
                (
                    "main_judge",
                    models.ForeignKey(
                        blank=True,
                        help_text="Обязателен для ранговых/квестовых боёв; в тренировочных — по усмотрению мастеров",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles_as_main_judge",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="главный судья",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="Запись создаёт только судья/админ — без самозаявления участников",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="battles_recorded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто зафиксировал",
                    ),
                ),
                (
                    "side_judge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles_as_side_judge",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="боковой судья",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Может отсутствовать — ничья/дубль",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="battles_won",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="победитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "бой",
                "verbose_name_plural": "бои",
                "ordering": ["-date"],
                "permissions": [
                    ("can_record_battles", "Может фиксировать результаты боёв")
                ],
            },
        ),
    ]
