# Generated by Django 6.1.1 on 2026-09-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="вопрос")),
                ("answer", models.TextField(verbose_name="ответ")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Необязательная группировка, например «Регистрация», «Магазин»",
                        max_length=100,
                        verbose_name="категория",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
            ],
            options={
                "verbose_name": "вопрос FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["category", "order", "id"],
            },
        ),
    ]
