# Generated by Django 6.1.1 on 2026-09-14 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0002_seed_subscriptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="день недели",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="начало")),
                ("end_time", models.TimeField(verbose_name="окончание")),
                ("title", models.CharField(max_length=200, verbose_name="название")),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="место"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="заметки")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активно"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Опционально — если занятие соответствует одной из разовых активностей",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_entries",
                        to="subscriptions.activityprice",
                        verbose_name="активность",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись расписания",
                "verbose_name_plural": "расписание",
                "ordering": ["weekday", "start_time"],
                "permissions": [
                    ("can_manage_schedule", "Может редактировать расписание клуба")
                ],
            },
        ),
    ]
