# Generated by Django 6.1.1 on 2026-09-15 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Что в общем означает этот титул",
                        verbose_name="описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "титул",
                "verbose_name_plural": "титулы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TitleAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="за что получен")),
                (
                    "granted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="выдан"),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="titles_granted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто выдал",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="titles.title",
                        verbose_name="титул",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="title_awards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "выданный титул",
                "verbose_name_plural": "выданные титулы",
                "ordering": ["-granted_at"],
                "permissions": [
                    ("can_grant_titles", "Может выдавать титулы пользователям")
                ],
                "unique_together": {("user", "title")},
            },
        ),
    ]
