# Generated by Django 6.1.1 on 2026-09-15 06:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fundraiser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="название")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fundraisers/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "goal_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="цель, BYN"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("completed", "Завершён"),
                            ("cancelled", "Отменён"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="дата начала"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата окончания"
                    ),
                ),
            ],
            options={
                "verbose_name": "сбор средств",
                "verbose_name_plural": "сборы средств",
                "ordering": ["-start_date"],
                "permissions": [
                    (
                        "can_manage_fundraisers",
                        "Может управлять сборами средств и фиксировать взносы",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FundraiserContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contributor_name",
                    models.CharField(
                        blank=True,
                        help_text="Для гостя/внешнего донатера без аккаунта на сайте",
                        max_length=150,
                        verbose_name="имя донатера",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="сумма, BYN"
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="анонимный взнос"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="зафиксирован"
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если донатер — зарегистрированный участник клуба",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fundraiser_contributions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="участник клуба",
                    ),
                ),
                (
                    "fundraiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="fundraisers.fundraiser",
                        verbose_name="сбор",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fundraiser_contributions_recorded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто зафиксировал",
                    ),
                ),
            ],
            options={
                "verbose_name": "взнос",
                "verbose_name_plural": "взносы",
                "ordering": ["-created_at"],
            },
        ),
    ]
