# Generated by Django 6.1.1 on 2026-09-15 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="дата начала"
            ),
        ),
    ]
