# Generated by Django 6.1.1 on 2026-09-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ranks", "0003_alter_rankuprequest_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="EffectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Машиночитаемый код, например 'hp', 'damage', 'sign_slot'",
                        max_length=50,
                        unique=True,
                        verbose_name="код",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
            ],
            options={
                "verbose_name": "тип эффекта",
                "verbose_name_plural": "типы эффектов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "Обычный товар"),
                            ("potion", "Зелье/эликсир"),
                            ("scroll", "Свиток"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="категория",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Пусто — для эликсиров: по документу они не покупаются за фиксированную цену, а крафтятся мастером-алхимиком за рецепт, кроны и трофеи",
                        null=True,
                        verbose_name="цена, кроны",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ограничение количества; пусто = без лимита",
                        null=True,
                        verbose_name="остаток",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
                (
                    "toxicity",
                    models.CharField(
                        blank=True,
                        help_text="% токсичности разового применения (только для эликсиров). Текстовое поле — у части эликсиров ступенчатая токсичность («0% за первую, 30% за каждую следующую»)",
                        max_length=100,
                        verbose_name="токсичность",
                    ),
                ),
                (
                    "min_rank",
                    models.ForeignKey(
                        blank=True,
                        help_text="Минимальный ранг для использования; обязателен для эликсиров",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ranks.rank",
                        verbose_name="минимальный ранг",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ItemEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        blank=True,
                        help_text="Числовое значение эффекта, например +2 макс. ХП",
                        null=True,
                        verbose_name="значение",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("instant", "Мгновенный"),
                            ("temporary", "Временный"),
                            ("permanent", "Постоянный"),
                        ],
                        default="instant",
                        max_length=20,
                        verbose_name="длительность",
                    ),
                ),
                (
                    "duration_value",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Если временный — на сколько тактов/боёв",
                        null=True,
                        verbose_name="на сколько",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_effects",
                        to="shop.effecttype",
                        verbose_name="тип эффекта",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="shop.shopitem",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "эффект товара",
                "verbose_name_plural": "эффекты товара",
            },
        ),
    ]
