# Generated by Django 6.1.1 on 2026-09-14 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_seed_shop_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_paid",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Пусто — если выдано вручную без оплаты",
                        null=True,
                        verbose_name="уплачено, кроны",
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="получено"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Свиток возвращён мастеру / зелье выпито и т.п.",
                        verbose_name="использован",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="использован когда"
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пусто, если товар куплен самим пользователем",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_granted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто выдал вручную",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="shop.shopitem",
                        verbose_name="товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "покупка",
                "verbose_name_plural": "покупки",
                "ordering": ["-purchased_at"],
                "permissions": [
                    ("can_grant_items", "Может выдавать товары вручную без оплаты")
                ],
            },
        ),
    ]
