# Generated by Django 6.1.1 on 2026-09-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="schools/icons/",
                        verbose_name="иконка",
                    ),
                ),
                (
                    "emblem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="schools/emblems/",
                        verbose_name="герб",
                    ),
                ),
                (
                    "weapon_type",
                    models.CharField(
                        help_text="Например, «Полуторный меч»; для школ с несколькими типами оружия — перечисляется текстом",
                        max_length=255,
                        verbose_name="тип оружия",
                    ),
                ),
                (
                    "base_hp",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="базовое ХП"
                    ),
                ),
                (
                    "base_damage",
                    models.CharField(
                        blank=True,
                        help_text="Текстовое поле, а не число — например, у Лисы: «лук 2–3 (по дистанции), меч 1»",
                        max_length=255,
                        verbose_name="базовый урон",
                    ),
                ),
                (
                    "sign_slots",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="слоты знаков"
                    ),
                ),
                (
                    "intoxication_threshold",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="порог интоксикации, %"
                    ),
                ),
                (
                    "special_abilities",
                    models.TextField(blank=True, verbose_name="особенности"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("in_development", "В разработке"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "школа",
                "verbose_name_plural": "школы",
                "ordering": ["name"],
            },
        ),
    ]
