# Generated by Django 6.1.1 on 2026-09-15 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("club", "Клуб"),
                            ("master", "Мастер школы"),
                            ("armory", "Оружейня"),
                        ],
                        max_length=20,
                        verbose_name="тип владельца",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        help_text="Telegram, VK, Instagram и т.д.",
                        max_length=100,
                        verbose_name="платформа",
                    ),
                ),
                ("url", models.URLField(verbose_name="ссылка")),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="подпись"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Заполняется, только если тип владельца — «Мастер школы»",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "ссылка на соц-сеть",
                "verbose_name_plural": "ссылки на соц-сети",
                "ordering": ["owner_type", "platform"],
                "permissions": [
                    (
                        "can_manage_social_links",
                        "Может управлять ссылками клуба/оружейни/других мастеров",
                    )
                ],
            },
        ),
    ]
