# Generated by Django 6.1.1 on 2026-09-14 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Например, 🛡 или ⚔️",
                        max_length=16,
                        verbose_name="иконка/эмодзи",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Порядок в иерархии — используется для сортировки и проверки условий вида «и выше»",
                        unique=True,
                        verbose_name="порядок",
                    ),
                ),
            ],
            options={
                "verbose_name": "ранг",
                "verbose_name_plural": "ранги",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RankRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("level", "Уровень"),
                            ("wins_vs_rank", "Победы над рангом"),
                            ("rpg_wins", "РПГ-победы"),
                            ("journeyman_count", "Кол-во подмастерьев"),
                            ("master_count", "Кол-во мастеров"),
                            ("trial", "Испытание"),
                            ("monster_trophies", "Трофеи с монстров"),
                            ("quest_lines", "Квестовые линии"),
                            ("custom", "Другое"),
                        ],
                        max_length=30,
                        verbose_name="тип условия",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="значение"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Для нестандартных условий вроде «испытание травами»",
                        max_length=255,
                        verbose_name="описание",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="ranks.rank",
                        verbose_name="ранг",
                    ),
                ),
                (
                    "target_rank",
                    models.ForeignKey(
                        blank=True,
                        help_text="Для условий вида «N побед над членами ранга X и выше»",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ranks.rank",
                        verbose_name="целевой ранг",
                    ),
                ),
            ],
            options={
                "verbose_name": "требование ранга",
                "verbose_name_plural": "требования ранга",
            },
        ),
        migrations.CreateModel(
            name="RankReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("item", "Предмет"),
                            ("discount", "Скидка"),
                            ("board_placement", "Место на доске почёта"),
                            ("title", "Титул"),
                            ("slot", "Слот"),
                            ("custom", "Другое"),
                        ],
                        max_length=30,
                        verbose_name="тип награды",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="значение"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="описание"
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="ranks.rank",
                        verbose_name="ранг",
                    ),
                ),
            ],
            options={
                "verbose_name": "награда ранга",
                "verbose_name_plural": "награды ранга",
            },
        ),
        migrations.CreateModel(
            name="RankUpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="рассмотрена"
                    ),
                ),
                (
                    "from_rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ranks.rank",
                        verbose_name="текущий ранг",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто рассмотрел",
                    ),
                ),
                (
                    "to_rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ranks.rank",
                        verbose_name="желаемый ранг",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rank_up_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка на повышение ранга",
                "verbose_name_plural": "заявки на повышение ранга",
                "ordering": ["-created_at"],
            },
        ),
    ]
