# Generated by Django 6.1.1 on 2026-09-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ranks", "0002_seed_ranks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rankuprequest",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "can_approve_ranks",
                        "Может подтверждать заявки на повышение ранга",
                    )
                ],
                "verbose_name": "заявка на повышение ранга",
                "verbose_name_plural": "заявки на повышение ранга",
            },
        ),
    ]
